[tool.poetry]
name = "meetupjuly2024"
version = "0.1.0"
description = ""
authors = ["Sigal Shaharabani <sigals@tikalk.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langgraph = "^0.1.8"
jupyter = "^1.0.0"
python-dotenv = "1.0.1"
langchain_openai = "0.1.14"
couchbase = "^4.2.1"
langchain-couchbase = "^0.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
